apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: fax-over-ip-pod
spec:
  containers:
  - name: liveness
    image: pablitomilenios/fax-foip-fritzbox:version3
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
