version: '3'
services:
  faxing-service: 
    container_name: "FOIP-faxoverip-telephonecentral-container"
    #needs to be reconfigured for node:
    ports:
      - "8081:80"
    image: foip-t38-iax-containerbase
    # the following command keeps the container running forever:
    command: tail -F anything
