apiVersion: apps/v1
kind: Deployment
metadata:
  name: asterisk-app
  labels:
    running: asterisk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asterisk
  template:
    metadata:
      labels:
        app: asterisk
    spec:
      containers:
      - name: asterisk
        image: atalovin/asterisk
        ports:
        - containerPort: 3000
        - containerPort: 5060
        - containerPort: 5061
        - containerPort: 6060