apiVersion: apps/v1
kind: Deployment
metadata:
  name: faxoverip
  labels:
    running: faxoverip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faxoverip
  template:
    metadata:
      labels:
        app: faxoverip
    spec:
      containers:
      - name: faxoverip
        image: pablitomilenios/fax-foip-fritzbox:bt3
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
            - SYS_ADMIN
            - SYS_MODULE
        ports:
        - containerPort: 500
        - containerPort: 3000
        - containerPort: 4500
        - containerPort: 5060       
        - containerPort: 5061
        - containerPort: 6060
        - containerPort: 10000