apiVersion: apps/v1
kind: Deployment
metadata:
  name: faxoverip-app
  labels:
    running: faxoverip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faxoverip
  template:
    metadata:
      labels:
        app: faxoverip
    spec:
      containers:
      - name: faxoverip
        image: pablitomilenios/withvpn
        ports:
        - containerPort: 500
        - containerPort: 3000
        - containerPort: 5060
        - containerPort: 5061
        - containerPort: 6060