apiVersion: apps/v1
kind: Deployment
metadata:
  name: foip-app
  labels:
    running: foip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foip
  template:
    metadata:
      labels:
        app: foip
    spec:
      containers:
      - name: foip
        image: pablitomilenios/fax-foip-fritzbox:version16
        ports:
        - containerPort: 3000
        - containerPort: 5060
        - containerPort: 5061
        - containerPort: 6060