apiVersion: apps/v1
kind: Deployment
metadata:
  name: fax-over-ip-fritzbox
  labels:
    running: fax-over-ip-fritzbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fax-over-ip-fritzbox
  template:
    metadata:
      labels:
        app: fax-over-ip-fritzbox
    spec:
      containers:
      - name: fax-over-ip-fritzbox
        image: pablitomilenios/fritzbox-foip-fax-over-ip
        ports:
        - containerPort: 3000
        - containerPort: 5060
        - containerPort: 5061
        - containerPort: 6060